config/routes.rb
Rails.application.routes.draw do

  resources :wordorders
  post '/wordorder_update_serial', to: 'wordorders#update_serial'
  post '/load_wordorders', to: 'wordorders#load_wordorders'
  get '/wordorder_index_with_details', to: 'wordorders#index_with_details'

  resources :wordmaps
  post '/export_wordmaps_to_cardbox', to: 'wordmaps#export_wordmaps_to_cardbox'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :practice_parsers

  resources :booklists

  get 'agreements/like'
  get 'agreements/dislike'

  resources :comments

  resources :paces do
    get :autocomplete_lesson_title, on: :collection
  end
  post '/paces/choose_a_textbook', to: 'paces#choose_a_textbook'
  post '/paces/load_from_textbook', to: 'paces#load_from_textbook'

  resources :roadmaps do
    post 'single_words'
    post 'single_words_in_freq'
    post 'single_words_in_line'
    post 'meanful_words'
    post 'meanful_words_in_freq'
    post 'meanful_words_in_line'
  end
  post '/roadmaps/choose_begin_and_end', to: 'roadmaps#choose_begin_and_end'
  post '/roadmaps/compare_with_roadmap', to: 'roadmaps#compare_with_roadmap'
  get '/create_roadmap_for_textbook', to: 'roadmaps#create_roadmap_for_textbook'
  get '/update_roadmap_for_textbook', to: 'roadmaps#update_roadmap_for_textbook'
  get '/copy_to_new_roadmap', to: 'roadmaps#copy_to_new_roadmap'

  resources :meanings
  get '/search_meanings', to: 'meanings#search_meanings'

  resources :phonetic_notations
  get '/choose_phonetic_notations', to: 'phonetic_notations#choose_phonetic_notations'
  post '/load_phonetic_notations', to: 'phonetic_notations#load_phonetic_notations'

  resources :phonetics
  post '/phonetic/create_phonetic_for_word', to: 'phonetics#create_phonetic_for_word'
  get '/chinese_yinxu', to: 'phonetics#chinese_yinxu'
  get '/chinese_rhyme', to: 'phonetics#chinese_rhyme'
  get '/xxb_rhyme', to: 'phonetics#xxb_rhyme'
  get '/list_rhyme_words', to: 'phonetics#list_rhyme_words'

  resources :sentences

  resources :word_parsers
  get '/choose_dictionary', to: 'words#choose_dictionary'
  post '/load_dictionary', to: 'words#load_dictionary'

  resources :words do
    get "change_meanful"
    get "load_explain_from_baidu_hanyu"
    get "load_explain_from_baidu_dict"
    get "load_explain_from_youdao_dict"
  end
  post '/word/new_words_as_tutor', to: 'words#new_words_as_tutor'
  get '/search_words', to: 'words#search_words'
  get '/show_words', to: 'words#show_words'
  get '/words_have_word', to: 'words#words_have_word'
  get '/lessons_have_word', to: 'words#lessons_have_word'
  get '/word_comments', to: 'words#word_comments'
  get '/show_fragmentary_words', to: 'words#show_fragmentary_words'

  resources :words_reports do
    get 'show_word_n'
    get 'show_de1'
    get 'show_de2'
    get 'show_de3'
    get 'show_basic'
    get 'show_unmeanful_words'
    get 'show_meanful_words'
  end
  get 'compare_with_another', to: "words_reports#compare_with_another"
  post 'compare_report', to: "words_reports#compare_report"

  resources :examrooms

  resources :paperitems

  resources :papertests

  resources :papers

  resources :fees

  resources :quiz_items do
    get  "right"
    get  "wrong"
  end

  resources :quizzes

  mathjax 'mathjax'

  resources :withdraws

  resources :cashiers

  resources :receipts
  get 'person_receipts', to: "receipts#person_receipts"
  get 'person_onboards', to: "receipts#person_onboards"
  get 'who_online', to: "receipts#who_online"
  get 'off_onboard', to: "receipts#off_onboard"

  resources :onboards

  resources :classpersonscores

  resources :classgroupscores

  resources :players

  resources :teams do
    post 'join_team'
    post 'exit_team'
  end

  resources :sectionalizations do
    get 'choose_sectionalization'
  end
  get '/reset_sectionalization', to: 'sectionalizations#reset_sectionalization'

  resources :masters

  resources :cards do
    get 'well_done'
    get 'try_again'
    get 'pass_card'
  end
  post '/cards/add_to_cardbox', to: 'cards#add_to_cardbox'
  post '/cards/multiple_operate', to: 'cards#multiple_operate'
  get '/list_right_cards', to: 'cards#list_right_cards'
  post '/search_right_cards', to: 'cards#search_right_cards'
  get 'card_download_practices', to: "cards#download_practices"
  get 'card_jquerymobile', to: "cards#jquerymobile"

  resources :cardboxes do
    get 'turn_cards'
    post 'copy_cardbox_for_me'
  end
  post '/cardboxes/append_to_cardbox', to: 'cardboxes#append_to_cardbox'
  get '/share_cardboxes', to: 'cardboxes#share_cardboxes'

  get 'download_csv', to: "badrecords#download_csv"
  resources :badrecords do
    get 'finish_badrecord'
    get 'restore_badrecord'
  end
  post '/badrecords/finish_badrecords_in_batch', to: 'badrecords#finish_badrecords_in_batch'

  resources :cadres

  resources :exercises
  get "/new_many_exercises", to: 'exercises#new_many_exercises'
  post "/add_many_practices", to: 'exercises#add_many_practices'
  post "/import_exercises_from_cardbox", to: "exercises#import_exercises_from_cardbox"
  get "/export_exercises_to_cardbox", to: "exercises#export_exercises_to_cardbox"

  resources :subjects

  resources :teachers

  resources :observations

  resources :homeworks

  resources :complaints

  get 'quit_discussion', to: 'discussions#quit_discussion'
  resources :discussions do
    delete 'end_discussion'
  end

  resources :members
  post '/members/create_members_in_batch', to: 'members#create_members_in_batch'

  resources :classrooms
  get '/quit_classroom', to: 'classrooms#quit_classroom'
  get '/class_badrecords', to: 'classrooms#class_badrecords'
  get '/class_finish_badrecords', to: 'classrooms#class_finish_badrecords'

  resources :justices

  resources :evaluations do
    get 'delete_picture_ya'
  end

  get '/hello' => "me#summary", as: :user_root
  get 'me/summary'
  get 'me/teacher_office'
  get 'me/point_card'
  get 'me/justify'
  get 'me/assign_homeworks'
  get 'me/my_homeworks'
  get 'me/as_a_teacher'
  get 'me/as_a_student'
  get 'me/my_receipts'

  resources :plans
  get '/talkshow_yml', to: 'plans#talkshow_yml'

  resources :teachings
  get '/quit_teaching', to: 'teachings#quit'

  resources :catalogs do
    get :autocomplete_lesson_title, on: :collection
  end
  get '/catalogs_quick_append', to: 'catalogs#quick_append'

  resources :textbooks do
    get 'single_words'
    get 'single_words_in_freq'
    get 'meanful_words'
    get 'meanful_words_in_freq'
    get 'words_analysis'
  end

  resources :practices do
    get 'delete_picture_q'
    get 'delete_picture_a'
    get 'add_to_paper'
    get 'analysize'
    get :autocomplete_lesson_title, on: :collection
  end
  post '/practices/create_practices_in_batch', to: 'practices#create_practices_in_batch'
  get '/list_all_practices', to: 'practices#list_all_practices'
  get '/search_practices', to: 'practices#search_practices'
  post'/practice_add_to_lesson', to: 'practices#practice_add_to_lesson'
  post'/practice_delete_from_lesson', to: 'practices#practice_delete_from_lesson'
  post'/practice_add_to_tutor', to: 'practices#practice_add_to_tutor'
  post '/practice_copy_to_another_lesson', to: "practices#copy_to_another_lesson"
  post'/practice_change_to_lesson', to: 'practices#practice_change_to_lesson'
  get '/practice_all_in_table', to: 'practices#all_in_table'

  resources :tutors do
    get :autocomplete_lesson_title, on: :collection
    get 'delete_picture1'
    get 'delete_picture2'
    get 'show_with_lesson'
    get 'just_for_show'
  end
  get '/tutor/new_link_to_lesson', to: 'tutors#new_link_to_lesson'
  post '/tutor/create_link_to_lesson', to: 'tutors#create_link_to_lesson'
  get '/tutor/to_practice', to: 'tutors#to_practice'
  get '/tutor/create_pinyin_help_tutor', to: "tutors#create_pinyin_help_tutor"
  post '/tutor/choose_a_lesson', to: "tutors#choose_a_lesson"
  post '/tutor/copy_to_another_lesson', to: "tutors#copy_to_another_lesson"
  post '/tutor/append_cardbox_link', to: "tutors#append_cardbox_link"
  get 'tutor_download_exercises', to: "tutors#download_exercises"
  get '/tutor/create_multi_pinyin_tutor', to: "tutors#create_multi_pinyin_tutor"
  get '/tutor_create_pinyin_page_for_tutor', to: "tutors#create_pinyin_page_for_tutor"
  get '/tutor_create_explain_page_for_tutor', to: "tutors#create_explain_page_for_tutor"
  get '/tutor_find_sentences_with_words', to: "tutors#find_sentences_with_words"
  get '/tutor_proviso_as_practice_material', to: 'tutors#tutor_proviso_as_practice_material'
  get '/tutor_search_tutors', to: 'tutors#search_tutors'
  get '/tutor_new_sentences_show', to: 'tutors#new_sentences_show'
  get '/tutor_words_consist_of_chinese_words', to: 'tutors#words_consist_of_chinese_words'

  get 'lessons_in_content_length',  to: 'lessons#lessons_in_content_length'
  resources :lessons do
    get :autocomplete_lesson_title, on: :collection
    get 'delete_picture'
    get 'easy_teaching'
    get 'words_analysis'
    get 'as_tutor_link'
  end
  get '/lesson/as_tutor', to: 'lessons#as_tutor'
  post '/lesson/to_tutor', to: 'lessons#to_tutor'
  get '/choose_a_textbook', to: 'lessons#choose_a_textbook'
  get '/lesson_quickly_find_similar_lessons', to: 'lessons#lesson_quickly_find_similar_lessons'
  get '/lesson_same_author_lessons', to: 'lessons#lesson_same_author_lessons'
  get '/lesson_similar_title_lessons', to: 'lessons#lesson_similar_title_lessons'
  get '/lesson_similar_time_lessons', to: 'lessons#lesson_similar_time_lessons'
  get '/lesson_content_as_practice_material', to: 'lessons#lesson_content_as_practice_material'
  post '/lesson_compare_with_wordmap', to: 'lessons#compare_with_wordmap'
  post '/lesson_compare_single_with_wordmap', to: 'lessons#compare_single_with_wordmap'
  get '/search_in_textbook', to: 'lessons#search_in_textbook'

  devise_for :users, controllers: { sessions: "users/sessions" }

  scope "/admin" do
    resources :users
  end
  post "set_vip_user", to: "users#set_vip_user"
  post "set_normal_user", to: "users#set_normal_user"

app/models/practice.rb
class Practice < ApplicationRecord
  resourcify
  belongs_to :user
  belongs_to :tutor, optional: true
  belongs_to :lesson, optional: true
  has_many :evaluations, dependent: :destroy
  has_many :justices, dependent: :destroy
  has_many :exercises, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :quiz_items, dependent: :destroy
  has_many :practice_parsers
  has_many :lesson_practices
  has_many :lessons, through: :lesson_practices

  has_attached_file :picture_q
  validates_attachment_file_name :picture_q, :matches => [/png\Z/, /jpe?g\Z/]
  validates_attachment_content_type :picture_q, :content_type => /\Aimage\/.*\Z/
  has_attached_file :picture_a
  validates_attachment_file_name :picture_a, :matches => [/png\Z/, /jpe?g\Z/]
  validates_attachment_content_type :picture_a, :content_type => /\Aimage\/.*\Z/

  acts_as_paranoid
  validates :question, :answer, presence: true

  # 这个方法对练习题进行分析。
  def analysis_practice
    practice_id = self.id
    practice_content = self.question +  self.answer
    practice_content.gsub!(/<(\w|\/)+[^>]*>/, "") # 除去html标签
    word_part_content =  []

    word_part_content << practice_content.scan(/\w+/)
    word_part_content << practice_content.scan(/[\u4e00-\u9fa5]/)
    word_part_content.flatten!
    word_part_content.uniq!
    word_parsers_params = []
    if self.practice_parsers.empty?
      words_id = Word.where(name: word_part_content).pluck(:id)
      words_id.each{|w| word_parsers_params << {practice_id: practice_id, word_id: w} }
    else
        new_words_id = Word.where(name: word_part_content).pluck(:id)
        old_words_id = PracticeParser.where(practice_id: practice_id).pluck(:word_id)
        bad_words_id = old_words_id - new_words_id
        PracticeParser.where(practice_id: practice_id, word_id: bad_words_id).destroy_all
        good_words_id = new_words_id - old_words_id
        good_words_id.each{|w| word_parsers_params << {practice_id: practice_id, word_id: w} }
    end
    PracticeParser.create(word_parsers_params)
  end

=begin
  # 将practice原来的lesson_id字段迁移到lesson_practice里。
  def self.move_to_lesson_practices
    Practice.find_each do |practice|
      LessonPractice.create(practice_id: practice.id, lesson_id: practice.lesson_id)
    end
  end
=end

end

=begin
id
title 标题
material 材料
question 问题
labelname 可以废除，没有实际意义
answer 答案
user_id 只有所有者才能修改，但其他人可以将题目给自己重新复制一份后修改
tutor_id  应该废除，改为多对多
lesson_id  应该废除，改为多对多
activate  应该废除，没有实际意义
score 分值
用图片展示问题, 应该废除，用ckeditor已经解决这个问题
picture_q_file_name
picture_q_content_type
picture_q_file_size
picture_q_updated_at
用图片展示答案， 应该废除，用ckeditor已经解决这个问题
picture_a_file_name
picture_a_content_type
picture_a_file_size
picture_a_updated_at
统计指标
mean  平均分
mode  方差
stdev 标准差
difficulty  难度

created_at
deleted_at
=end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/index.html.erb
<%- model_class = Practice -%>

<% unless current_user.has_role? :admin %>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <div class="btn-group" role="btn-group" arial-label="manage">
      <%= link_to t('.new', :default => t("helpers.links.new")), new_practice_path, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.new', :default => [:"helpers.titles.new"], :model => model_class.model_name.human.titleize) %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
          list_all_practices_path, :class => 'btn btn-default', tabindex: 54, "data-toggle": "tooltip", "data-placement": "bottom", title: '所有习题'  %>
    </div>
    <div class="btn-group" role="btn-group" arial-label="operation">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" tabindex="60" >
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "表格视图", practice_all_in_table_path, tabindex: 61 %></li>
        <li><%= link_to "管理卡片盒", cardboxes_path, tabindex: 62 %></li>
        <li><%= link_to "查看辅导", tutors_path, tabindex: 63 %></li>
      </ul>
    </div>
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <%= link_to t('.up', :default => t("helpers.links.up")), lesson_path(@lesson), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.up', default: t("helpers.titles.up"), :model => t("activerecord.models.lesson")) %>
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <h3>《<%= @lesson.title %>》一课的所有练习</h3>
</div>

<% unless @order_type == nil %> 
<%= link_to '默认按分数排序', practices_url, class: "btn btn-default" %>
<% end %>
<% unless @order_type == "created_at" %> 
<%= link_to '按创建时间排序', practices_url(order_type: 'created_at'), class: "btn btn-default" %>
<% end %>
<% unless @order_type == "title" %> 
<%= link_to '按标题排序', practices_url(order_type: 'title'), class: "btn btn-default" %>
<% end %>
<% unless @order_type == "labelname" %> 
<%= link_to '按标签排序', practices_url(order_type: 'labelname'), class: "btn btn-default" %>
<% end %>
<% unless @order_type == "question" %> 
<%= link_to '按问题排序', practices_url(order_type: 'question'), class: "btn btn-default" %>
<% end %>

<% if current_user.id == @lesson.user_id %>
  <button class="btn btn-default pull-right" type="button" data-toggle="collapse" data-target="#collapseCreatePracticesInBatch" aria-expanded="false" aria-controls="collapseCreatePracticesInBatch">
    批量新添练习
  </button>
  <div class="collapse" id="collapseCreatePracticesInBatch">
    <div class="well">
      <p>注意：</p>
      <ul>
        <li>上传的文件必须是CSV文件，包含“标题”、“材料”、“问题”、“答案”、“分值”和“标签”六列。其中“分值”一栏可以为空</li>
        <li>CSV文件是一种用逗号隔开数据的文本文件，这种文件也可使用Excel等程序通过“另存为”功能生成。
      </ul>
      <%= form_tag "/practices/create_practices_in_batch", multipart: true, class: 'form-inline' do %>
        <div class="control-group">
        <%= file_field_tag "csv_file", accept: "text/csv", class: 'form-control' %>
        <%= submit_tag "上传文件", class: 'btn btn-info form-control' %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= form_tag "/cards/add_to_cardbox", class: 'form-inline' do %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><input type="checkbox" id="checkbox_select_all_practices" /></th>
      <th>标题</th>
      <th>材料</th>
      <th>问题</th>
      <th>分值</th>
      <th>标签</th>
      <th colspan="2"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= check_box_tag "practice_id[]", practice.id %></td>
        <td><%= practice.title.first(20) %></td>
        <td>
          <% if practice.material %>
            <%= practice.material.gsub(/(<(\w|\/)+[^>]*>|\s)/, "").first(20) %>
          <% end %>
        </td>
        <td><%= link_to practice.question.gsub(/(<(\w|\/)+[^>]*>|\s)/, "").first(20), practice_path(practice), class: "btn-xs btn-link" %></td>
        <td><%= practice.score %></td>
        <td><%= practice.labelname %></td>
        <td>
          <% if e = Evaluation.find_by(practice_id: practice.id, user_id: current_user.id) %>
            <%= link_to "重做", edit_evaluation_path(e), class: "btn btn-xs btn-default" %>
          <% else %>
            <%= link_to "做题", new_evaluation_path(practice_id: practice), class: "btn btn-xs btn-default" %>
         <% end %>
          <% if current_user.id == practice.user_id %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), 
              edit_practice_path(practice), 
              :class => 'btn btn-default btn-xs', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.edit', :default => [:"helpers.titles.edit"], :model => model_class.model_name.human.titleize) %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), 
              practice_path(practice), 
              :method => :delete, 
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, 
              :class => 'btn btn-xs btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.delete', :default => [:"helpers.titles.delete"], :model => model_class.model_name.human.titleize) %>
            <% if session[:lesson_id] %>
              <%= link_to "删除连接", 
                practice_delete_from_lesson_path(practice_id: practice.id, lesson_id: session[:lesson_id]), 
                :method => :post, 
                :data => { :confirm => "确定不再作为本文的习题？" }, 
                :class => 'btn btn-xs btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.delete', :default => [:"helpers.titles.delete"], :model => model_class.model_name.human.titleize) %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseAddToCardbox" aria-expanded="false" aria-controls="collapseAddToCardbox">
  将所选习题添加到卡片盒中
</button>
<div class="collapse" id="collapseAddToCardbox">
  <div class="well">
    <div class="control-group">
      <%= select_tag :cardbox_id, options_for_select(Cardbox.where(user_id: current_user.id, lesson_id: session[:lesson_id]).collect{ |cardbox| [cardbox.id.to_s + " - " + cardbox.name, cardbox.id]}), {prompt: "请选择一个卡片盒", class: 'form-control col-md-4'} %>
    </div>
    <%= submit_tag "提交", :class => 'btn btn-primary' %>
  </div>
</div>

<% end %>

<% else %>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:material) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:answer) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:labelname) %></th>
      <th><%= model_class.human_attribute_name(:mean) %></th>
      <th><%= model_class.human_attribute_name(:mode) %></th>
      <th><%= model_class.human_attribute_name(:stdve) %></th>
      <th><%= model_class.human_attribute_name(:difficulty) %></th>
      <th><%= model_class.human_attribute_name(:activate) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:lesson_id) %></th>
      <th><%= model_class.human_attribute_name(:tutor_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= link_to practice.id, practice_path(practice) %></td>
        <td><%= practice.title %></td>
        <td><%= practice.material %></td>
        <td><%= practice.question %></td>
        <td><%= practice.answer %></td>
        <td><%= practice.score %></td>
        <td><%= practice.labelname %></td>
        <td><%= practice.mean %></td>
        <td><%= practice.mode %></td>
        <td><%= practice.stdve %></td>
        <td><%= practice.difficulty %></td>
        <td><%= practice.activate %></td>
        <td><%= practice.user_id %></td>
        <td><%= practice.lesson_id %></td>
        <td><%= practice.tutor_id %></td>
        <td><%=l practice.created_at %></td>
        <td><%=l practice.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_practice_path(practice), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      practice_path(practice),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_practice_path,
	    :class => 'btn btn-primary' %>
<% end %>

app/views/practices/list_all_practices.html.erb
<%- model_class = Practice -%>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <div class="btn-group" role="btn-group" arial-label="manage">
      <%= link_to t('.new', :default => t("helpers.links.new")), new_practice_path, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.new', :default => [:"helpers.titles.new"], :model => model_class.model_name.human.titleize) %>
    </div>
    <div class="btn-group" role="btn-group" arial-label="operation">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" tabindex="60" >
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "管理卡片盒", cardboxes_path, tabindex: 61 %></li>
      </ul>
    </div>
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <h3>所有练习</h3>
</div>
<div>
<%= form_tag "/search_practices", method: :get, class: 'form-inline' do %>
  <div class="form-group">
    <%= search_field_tag :key_word, "", class: "form-control" %>
    <%= submit_tag "搜索习题", class: "form-control" %>
  </div>
<% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr class="info">
      <th>id</th>
      <th>标题</th>
      <th>材料</th>
      <th>问题</th>
      <th>分值</th>
      <th>标签</th>
      <th colspan="2"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.id %></td>
        <td><%= practice.title %></td>
        <td><%= practice.material %></td>
        <td><%= link_to practice.question.gsub(/(<(\w|\/)+[^>]*>|\s)/, ""), practice_path(practice), class: "btn-xs btn-link" %></td>
        <td><%= practice.score %></td>
        <td><%= practice.labelname %></td>
        <td>
          <% if current_user.id == practice.user_id %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), 
              edit_practice_path(practice), 
              :class => 'btn btn-default btn-xs', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.edit', :default => [:"helpers.titles.edit"], :model => model_class.model_name.human.titleize) %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), 
              practice_path(practice), 
              :method => :delete, 
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, 
              :class => 'btn btn-xs btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.delete', :default => [:"helpers.titles.delete"], :model => model_class.model_name.human.titleize) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @practices %>