config/routes.rb
  get '/wordorder_index_with_details', to: 'wordorders#index_with_details'

  resources :wordmaps
  post '/export_wordmaps_to_cardbox', to: 'wordmaps#export_wordmaps_to_cardbox'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :practice_parsers

  resources :booklists

  get 'agreements/like'
  get 'agreements/dislike'

  resources :comments

  resources :paces do
    get :autocomplete_lesson_title, on: :collection
  end
  post '/paces/choose_a_textbook', to: 'paces#choose_a_textbook'
  post '/paces/load_from_textbook', to: 'paces#load_from_textbook'

  resources :roadmaps do
    post 'single_words'
    post 'single_words_in_freq'
    post 'single_words_in_line'
    post 'meanful_words'
    post 'meanful_words_in_freq'
    post 'meanful_words_in_line'
  end
  post '/roadmaps/choose_begin_and_end', to: 'roadmaps#choose_begin_and_end'
  post '/roadmaps/compare_with_roadmap', to: 'roadmaps#compare_with_roadmap'
  get '/create_roadmap_for_textbook', to: 'roadmaps#create_roadmap_for_textbook'
  get '/update_roadmap_for_textbook', to: 'roadmaps#update_roadmap_for_textbook'
  get '/copy_to_new_roadmap', to: 'roadmaps#copy_to_new_roadmap'

  resources :meanings
  get '/search_meanings', to: 'meanings#search_meanings'

  resources :phonetic_notations
  get '/choose_phonetic_notations', to: 'phonetic_notations#choose_phonetic_notations'
  post '/load_phonetic_notations', to: 'phonetic_notations#load_phonetic_notations'

  resources :phonetics
  post '/phonetic/create_phonetic_for_word', to: 'phonetics#create_phonetic_for_word'
  get '/chinese_yinxu', to: 'phonetics#chinese_yinxu'
  get '/chinese_rhyme', to: 'phonetics#chinese_rhyme'
  get '/xxb_rhyme', to: 'phonetics#xxb_rhyme'
  get '/list_rhyme_words', to: 'phonetics#list_rhyme_words'

  resources :sentences

  resources :word_parsers
  get '/choose_dictionary', to: 'words#choose_dictionary'
  post '/load_dictionary', to: 'words#load_dictionary'

  resources :words do
    get "change_meanful"
    get "load_explain_from_baidu_hanyu"
    get "load_explain_from_baidu_dict"
    get "load_explain_from_youdao_dict"
  end
  post '/word/new_words_as_tutor', to: 'words#new_words_as_tutor'
  get '/search_words', to: 'words#search_words'
  get '/show_words', to: 'words#show_words'
  get '/words_have_word', to: 'words#words_have_word'
  get '/lessons_have_word', to: 'words#lessons_have_word'
  get '/word_comments', to: 'words#word_comments'
  get '/show_fragmentary_words', to: 'words#show_fragmentary_words'

  resources :words_reports do
    get 'show_word_n'
    get 'show_de1'
    get 'show_de2'
    get 'show_de3'
    get 'show_basic'
    get 'show_unmeanful_words'
    get 'show_meanful_words'
  end
  get 'compare_with_another', to: "words_reports#compare_with_another"
  post 'compare_report', to: "words_reports#compare_report"

  resources :examrooms

  resources :paperitems

  resources :papertests

  resources :papers

  resources :fees

  resources :quiz_items do
    get  "right"
    get  "wrong"
  end

  resources :quizzes

  mathjax 'mathjax'

  resources :withdraws

  resources :cashiers

  resources :receipts
  get 'person_receipts', to: "receipts#person_receipts"
  get 'person_onboards', to: "receipts#person_onboards"
  get 'who_online', to: "receipts#who_online"
  get 'off_onboard', to: "receipts#off_onboard"

  resources :onboards

  resources :classpersonscores

  resources :classgroupscores

  resources :players

  resources :teams do
    post 'join_team'
    post 'exit_team'
  end

  resources :sectionalizations do
    get 'choose_sectionalization'
  end
  get '/reset_sectionalization', to: 'sectionalizations#reset_sectionalization'

  resources :masters

  resources :cards do
    get 'well_done'
    get 'try_again'
    get 'pass_card'
  end
  post '/cards/add_to_cardbox', to: 'cards#add_to_cardbox'
  post '/cards/multiple_operate', to: 'cards#multiple_operate'
  get '/list_right_cards', to: 'cards#list_right_cards'
  post '/search_right_cards', to: 'cards#search_right_cards'
  get 'card_download_practices', to: "cards#download_practices"
  get 'card_jquerymobile', to: "cards#jquerymobile"

  resources :cardboxes do
    get 'turn_cards'
    post 'copy_cardbox_for_me'
  end
  post '/cardboxes/append_to_cardbox', to: 'cardboxes#append_to_cardbox'
  get '/share_cardboxes', to: 'cardboxes#share_cardboxes'

  get 'download_csv', to: "badrecords#download_csv"
  resources :badrecords do
    get 'finish_badrecord'
    get 'restore_badrecord'
  end
  post '/badrecords/finish_badrecords_in_batch', to: 'badrecords#finish_badrecords_in_batch'

  resources :cadres

  resources :exercises
  get "/new_many_exercises", to: 'exercises#new_many_exercises'
  post "/add_many_practices", to: 'exercises#add_many_practices'
  post "/import_exercises_from_cardbox", to: "exercises#import_exercises_from_cardbox"
  get "/export_exercises_to_cardbox", to: "exercises#export_exercises_to_cardbox"

  resources :subjects

  resources :teachers

  resources :observations

  resources :homeworks

  resources :complaints

  get 'quit_discussion', to: 'discussions#quit_discussion'
  resources :discussions do
    delete 'end_discussion'
  end

  resources :members
  post '/members/create_members_in_batch', to: 'members#create_members_in_batch'

  resources :classrooms
  get '/quit_classroom', to: 'classrooms#quit_classroom'
  get '/class_badrecords', to: 'classrooms#class_badrecords'
  get '/class_finish_badrecords', to: 'classrooms#class_finish_badrecords'

  resources :justices

  resources :evaluations do
    get 'delete_picture_ya'
  end

  get '/hello' => "me#summary", as: :user_root
  get 'me/summary'
  get 'me/teacher_office'
  get 'me/point_card'
  get 'me/justify'
  get 'me/assign_homeworks'
  get 'me/my_homeworks'
  get 'me/as_a_teacher'
  get 'me/as_a_student'
  get 'me/my_receipts'

  resources :plans
  get '/talkshow_yml', to: 'plans#talkshow_yml'

  resources :teachings
  get '/quit_teaching', to: 'teachings#quit'

  resources :catalogs do
    get :autocomplete_lesson_title, on: :collection
  end
  get '/catalogs_quick_append', to: 'catalogs#quick_append'

  resources :textbooks do
    get 'single_words'
    get 'single_words_in_freq'
    get 'meanful_words'
    get 'meanful_words_in_freq'
    get 'words_analysis'
  end

  resources :practices do
    get 'delete_picture_q'
    get 'delete_picture_a'
    get 'add_to_paper'
    get 'analysize'
    get :autocomplete_lesson_title, on: :collection
  end
  post '/practices/create_practices_in_batch', to: 'practices#create_practices_in_batch'
  get '/list_all_practices', to: 'practices#list_all_practices'
  get '/search_practices', to: 'practices#search_practices'
  post'/practice_add_to_lesson', to: 'practices#practice_add_to_lesson'
  post'/practice_delete_from_lesson', to: 'practices#practice_delete_from_lesson'
  post'/practice_add_to_tutor', to: 'practices#practice_add_to_tutor'
  post '/practice_copy_to_another_lesson', to: "practices#copy_to_another_lesson"
  post'/practice_change_to_lesson', to: 'practices#practice_change_to_lesson'
  get '/practice_all_in_table', to: 'practices#all_in_table'

  resources :tutors do
    get :autocomplete_lesson_title, on: :collection
    get 'delete_picture1'
    get 'delete_picture2'
    get 'show_with_lesson'
    get 'just_for_show'
  end
  get '/tutor/new_link_to_lesson', to: 'tutors#new_link_to_lesson'
  post '/tutor/create_link_to_lesson', to: 'tutors#create_link_to_lesson'
  get '/tutor/to_practice', to: 'tutors#to_practice'
  get '/tutor/create_pinyin_help_tutor', to: "tutors#create_pinyin_help_tutor"
  post '/tutor/choose_a_lesson', to: "tutors#choose_a_lesson"
  post '/tutor/copy_to_another_lesson', to: "tutors#copy_to_another_lesson"
  post '/tutor/append_cardbox_link', to: "tutors#append_cardbox_link"
  get 'tutor_download_exercises', to: "tutors#download_exercises"
  get '/tutor/create_multi_pinyin_tutor', to: "tutors#create_multi_pinyin_tutor"
  get '/tutor_create_pinyin_page_for_tutor', to: "tutors#create_pinyin_page_for_tutor"
  get '/tutor_create_explain_page_for_tutor', to: "tutors#create_explain_page_for_tutor"
  get '/tutor_find_sentences_with_words', to: "tutors#find_sentences_with_words"
  get '/tutor_proviso_as_practice_material', to: 'tutors#tutor_proviso_as_practice_material'
  get '/tutor_search_tutors', to: 'tutors#search_tutors'
  get '/tutor_new_sentences_show', to: 'tutors#new_sentences_show'
  get '/tutor_words_consist_of_chinese_words', to: 'tutors#words_consist_of_chinese_words'

  get 'lessons_in_content_length',  to: 'lessons#lessons_in_content_length'
  resources :lessons do
    get :autocomplete_lesson_title, on: :collection
    get 'delete_picture'
    get 'easy_teaching'
    get 'words_analysis'
    get 'as_tutor_link'
  end
  get '/lesson/as_tutor', to: 'lessons#as_tutor'
  post '/lesson/to_tutor', to: 'lessons#to_tutor'
  get '/choose_a_textbook', to: 'lessons#choose_a_textbook'
  get '/lesson_quickly_find_similar_lessons', to: 'lessons#lesson_quickly_find_similar_lessons'
  get '/lesson_same_author_lessons', to: 'lessons#lesson_same_author_lessons'
  get '/lesson_similar_title_lessons', to: 'lessons#lesson_similar_title_lessons'
  get '/lesson_similar_time_lessons', to: 'lessons#lesson_similar_time_lessons'
  get '/lesson_content_as_practice_material', to: 'lessons#lesson_content_as_practice_material'
  post '/lesson_compare_with_wordmap', to: 'lessons#compare_with_wordmap'
  post '/lesson_compare_single_with_wordmap', to: 'lessons#compare_single_with_wordmap'
  get '/search_in_textbook', to: 'lessons#search_in_textbook'

  devise_for :users, controllers: { sessions: "users/sessions" }

  scope "/admin" do
    resources :users
  end
  post "set_vip_user", to: "users#set_vip_user"
  post "set_normal_user", to: "users#set_normal_user"
  post "reset_password", to: "users#reset_password"

  mount Ckeditor::Engine => '/ckeditor'

  get '/search_lesson', to: 'site#search_lesson'
  get '/search_sentences', to: 'site#search_sentences'

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  belongs_to :classroom
  belongs_to :subject
  resourcify
  acts_as_paranoid
  validates :user_id, :classroom_id, :mentor, :subject_id,  presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :be_a_master, except: [:index, :show]

  # GET /teachers
  # GET /teachers.json
  def index
    if current_user.has_role? :admin 
      @teachers = Teacher.all
    else
      @classroom = Classroom.find(session[:classroom_id])
      @teachers = Teacher.where(classroom_id: @classroom.id)
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    session[:teacher_id] = @teacher.id
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user_id = current_user.id
    @teacher.classroom_id = session[:classroom_id]

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: '成功为班级添加一位老师！' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:user_id, :classroom_id, :mentor, :deleted_at, :subject_id)
    end

    def be_a_master
      unless Master.find_by(user_id: current_user.id)
        redirect_back fallback_location: root_path, notice: "对不起，您暂时还没有老师的身份，无法进行操作。"
      end
    end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<% if current_user.has_role? :admin %>

<%- model_class = Teacher -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

<% else %>

<%- model_class = Teacher -%>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <div class="btn-group" role="btn-group" arial-label="manage">
      <%= link_to t('.back', :default => t("helpers.links.back")), teachers_path, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.back', :default => [:"helpers.titles.back"], :model => model_class.model_name.human.titleize) %>
    </div>
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

<% end %>

app/views/teachers/index.html.erb
<% if current_user.has_role? :admin %>  

<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:classroom_id) %></th>
      <th><%= model_class.human_attribute_name(:mentor) %></th>
      <th><%= model_class.human_attribute_name(:subject_id) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to teacher.id, teacher_path(teacher) %></td>
        <td><%= teacher.user_id %></td>
        <td><%= teacher.classroom_id %></td>
        <td><%= teacher.mentor %></td>
        <td><%= teacher.subject_id %></td>
        <td><%= teacher.deleted_at %></td>
        <td><%=l teacher.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

<% else %>

<%- model_class = Teacher -%>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <% if current_user.id = @classroom.user_id %>
    <div class="btn-group" role="btn-group" arial-label="manage">
      <%= link_to t('.new', :default => t("helpers.links.new")), new_teacher_path, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.new', :default => [:"helpers.titles.new"], :model => model_class.model_name.human.titleize) %>
    </div>
    <% end %>
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <%= link_to t('.up', :default => t("helpers.links.up")), classroom_url(@classroom), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.up', default: t("helpers.titles.up"), :model => t("activerecord.models.classroom")) %>
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <h3><%= @classroom.name %> 的 教师团队</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>科目</td>
      <th>教师</th>
      <th>参加时间</td>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.subject.name %></td>
        <td><%= link_to User.find(teacher.mentor).name, teacher_path(teacher) %></td>
        <td><%= teacher.created_at.strftime("%F") %></td>
        <td>
          <% if teacher.user_id == current_user.id %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.edit', :default => [:"helpers.titles.edit"], :model => model_class.model_name.human.titleize) %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.delete', :default => [:"helpers.titles.delete"], :model => model_class.model_name.human.titleize) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/teachers/new.html.erb
<% if current_user.has_role? :admin %>

<%- model_class = Teacher -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

<% else %>

<%- model_class = Teacher -%>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <div class="btn-group" role="btn-group" arial-label="manage">
      <%= link_to t('.back', :default => t("helpers.links.back")), teachers_path, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.back', :default => [:"helpers.titles.back"], :model => model_class.model_name.human.titleize) %>
    </div>
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <%= link_to t('.up', :default => t("helpers.links.up")), classroom_url(session[:classroom_id]), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.up', default: t("helpers.titles.up"), :model => t("activerecord.models.classroom")) %>
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

<% end %>

app/views/teachers/show.html.erb
<% if current_user.has_role? :admin %>  

<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @teacher.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:classroom_id) %>:</strong></dt>
  <dd><%= @teacher.classroom_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mentor) %>:</strong></dt>
  <dd><%= @teacher.mentor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deleted_at) %>:</strong></dt>
  <dd><%= @teacher.deleted_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% else %>

<%- model_class = Teacher -%>

<div class="container col-xs-11 col-sm-10 col-md-8 affix">
  <div class="btn-toolbar pull-right" role="toolbar" arial-label="toolbar">
    <!-- 管理功能 -->
    <div class="btn-group" role="group" arial-label="manage">
      <% if current_user.id == @teacher.user_id  %>
        <%= link_to t('.new', :default => t("helpers.links.new")), new_teacher_path, :class => 'btn btn-default', tabindex: 51, "data-toggle": "tooltip", "data-placement": "bottom", title: t('.new', :default => [:"helpers.titles.new"], :model => model_class.model_name.human.titleize) %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_teacher_path(@teacher), :class => 'btn btn-default', tabindex: 52, "data-toggle": "tooltip", "data-placement": "bottom", title: t('.edit', :default => [:"helpers.titles.edit"], :model => model_class.model_name.human.titleize) %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          teacher_path(@teacher),
          :method => 'delete',
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-default', tabindex: 53, "data-toggle": "tooltip", "data-placement": "bottom", title: t('.delete', :default => [:"helpers.titles.delete"], :model => model_class.model_name.human.titleize) %>
      <% end %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
        teachers_path, :class => 'btn btn-default', tabindex: 54, "data-toggle": "tooltip", "data-placement": "bottom", title: t('.back', :default => [:"helpers.titles.back"], :model => model_class.model_name.human.titleize)  %>
    </div>
   <!-- 附加功能 -->
    <div class="btn-group" role="btn-group" arial-label="operation">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <% if current_user.id == @teacher.mentor %>  <%# 如果不是本人，则不能发布作业 %>
            <%= link_to "布置作业", new_homework_path %>
          <% end %>
        </li>
        <li>
          <%= link_to "查看作业", homeworks_path %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to "添加课堂教学", new_discussion_url %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to "查看不良记录", badrecords_url %>
        </li>
      </ul>
    </div>
    <!-- 导航按钮 -->
    <div class="btn-group" role="btn-group" arial-label="navigation">
      <% if @previous_teacher %>
        <%= link_to t('.previous', :default => t("helpers.links.previous")), teacher_path(@previous_teacher), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.previous', default: t("helpers.titles.previous"), :model => t("activerecord.models.teacher")) %>
      <% end %>
      <% if @next_teacher %>
        <%= link_to t('.next', :default => t("helpers.links.next")), teacher_path(@next_teacher), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.next', default: t("helpers.titles.next"), :model => t("activerecord.models.teacher")) %>
      <% end %>
        <%= link_to t('.up', :default => t("helpers.links.up")), classroom_url(@teacher.classroom), class: 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.up', default: t("helpers.titles.up"), :model => t("activerecord.models.classroom")) %>
      <%= link_to t('.retreat', :default => t("helpers.links.retreat")), :back, :class => 'btn btn-default', "data-toggle": "tooltip", "data-placement": "bottom", title: t('.retreat', :default => [:"helpers.titles.retreat"]) %>
    </div>
  </div>
</div>

<div class="page-header">
  <% if current_user.id == @teacher.mentor %>
    <h3>我 在 <%= @teacher.classroom.name %> 的办公桌</h3>
  <% else %>
    <h3><%= User.find(@teacher.mentor.to_i).name %> 在 <%= @teacher.classroom.name %> 的办公桌</h3>
  <% end %>
</div>

          <%= link_to "查看作业", homeworks_path, class: "btn btn-default" %>
          <%= link_to "查看不良记录", badrecords_url, class: "btn btn-default" %>

<% end %>